"""intital commit

Revision ID: 0d4fb067bf92
Revises:
Create Date: 2026-05-22 11:44:59.461064

"""

from typing import Sequence, Union

from alembic import op
from geoalchemy2 import Geography
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0d4fb067bf92"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for Geography columns and UUID defaults used in this migration.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "industry_types",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("tier", sa.String(length=50), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "workers",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("firebase_uid", sa.String(), nullable=False),
        sa.Column("fcm_token", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country_code", sa.String(length=10), nullable=True),
        sa.Column("auth_number", sa.String(length=32), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("pincode", sa.String(length=20), nullable=True),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("status_approval_message_shown", sa.Boolean(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "is_online", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "is_available", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column("current_job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("firebase_uid"),
    )
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_workers_location
        ON workers
        USING gist (location)
        """)
    op.create_table(
        "category_skills",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("industry_type_id", sa.UUID(), nullable=False),
        sa.Column("tier", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["industry_type_id"], ["industry_types.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "industry_type_id", "name", name="uq_category_skill_industry_name"
        ),
    )
    op.create_table(
        "companies",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("firebase_uid", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("industry_id", sa.UUID(), nullable=False),
        sa.Column("gst_number", sa.String(), nullable=True),
        sa.Column("auth_phone", sa.String(), nullable=False),
        sa.Column("contact_person_name", sa.String(), nullable=True),
        sa.Column("contact_country_code", sa.String(), nullable=True),
        sa.Column("contact_phone", sa.String(), nullable=True),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("status_approval_message_shown", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["industry_id"], ["industry_types.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_email"),
    )
    op.create_index(
        op.f("ix_companies_firebase_uid"),
        "companies",
        ["firebase_uid"],
        unique=True,
        if_not_exists=True,
    )
    op.create_table(
        "worker_bank_details",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("account_holder_name", sa.String(), nullable=True),
        sa.Column("account_number", sa.String(), nullable=True),
        sa.Column("ifsc_code", sa.String(), nullable=True),
        sa.Column("upi_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_bank_details_worker_id"),
        "worker_bank_details",
        ["worker_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "worker_documents",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=120), nullable=True),
        sa.Column("document_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_documents_worker_id"),
        "worker_documents",
        ["worker_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "company_addresses",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("unit_name", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("pincode", sa.String(), nullable=False),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_company_addresses_location",
        "company_addresses",
        ["location"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_company_addresses_company_id"),
        "company_addresses",
        ["company_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "company_bank_details",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("account_holder_name", sa.String(), nullable=True),
        sa.Column("account_number", sa.String(), nullable=True),
        sa.Column("ifsc_code", sa.String(), nullable=True),
        sa.Column("upi_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_bank_details_company_id"),
        "company_bank_details",
        ["company_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "company_documents",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(), nullable=True),
        sa.Column("document_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_documents_company_id"),
        "company_documents",
        ["company_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_company_documents_document_type"),
        "company_documents",
        ["document_type"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "sub_category_skills",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("category_skill_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column("wage", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["category_skill_id"], ["category_skills.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category_skill_id", "name", name="uq_sub_category_skill_category_name"
        ),
    )
    op.create_table(
        "worker_skill_categories",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column("category_skill_id", sa.UUID(), nullable=False),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_skill_id"], ["category_skills.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "worker_id", "category_skill_id", name="uq_worker_category_unique"
        ),
    )
    op.create_index(
        op.f("ix_worker_skill_categories_category_skill_id"),
        "worker_skill_categories",
        ["category_skill_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_worker_skill_categories_worker_id"),
        "worker_skill_categories",
        ["worker_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "job_postings",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("skill_category_id", sa.UUID(), nullable=True),
        sa.Column("sub_category_id", sa.UUID(), nullable=True),
        sa.Column("industry_type_id", sa.UUID(), nullable=True),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("work_address", sa.Text(), nullable=True),
        sa.Column("nearby_landmark", sa.Text(), nullable=True),
        sa.Column(
            "scheduled_start_datetime", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("scheduled_end_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_duration", sa.String(), nullable=True),
        sa.Column("duration_type", sa.String(), nullable=True),
        sa.Column("shift", sa.String(), nullable=True),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workers", sa.Integer(), nullable=True),
        sa.Column("experience_required", sa.Integer(), nullable=True),
        sa.Column("wage", sa.Integer(), nullable=False),
        sa.Column("expected_total", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("language_preference", sa.String(), nullable=True),
        sa.Column("tool_provided", sa.Boolean(), nullable=True),
        sa.Column("tool_details", sa.Text(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column("assigned_worker_id", sa.UUID(), nullable=True),
        sa.Column(
            "posted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_worker_id"],
            ["workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["industry_type_id"],
            ["industry_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_category_id"],
            ["category_skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_category_id"],
            ["sub_category_skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_job_postings_location",
        "job_postings",
        ["location"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.create_index(
        "idx_job_scheduled_start",
        "job_postings",
        ["scheduled_start_datetime"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index("idx_job_status", "job_postings", ["status"], unique=False, if_not_exists=True)
    op.create_index(
        op.f("ix_job_postings_assigned_worker_id"),
        "job_postings",
        ["assigned_worker_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_job_postings_company_id"),
        "job_postings",
        ["company_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "worker_skill_subcategories",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column("sub_category_skill_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sub_category_skill_id"], ["sub_category_skills.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "worker_id", "sub_category_skill_id", name="uq_worker_subcategory_unique"
        ),
    )
    op.create_index(
        op.f("ix_worker_skill_subcategories_sub_category_skill_id"),
        "worker_skill_subcategories",
        ["sub_category_skill_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_worker_skill_subcategories_worker_id"),
        "worker_skill_subcategories",
        ["worker_id"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_worker_skill_subcategories_worker_id"),
        table_name="worker_skill_subcategories",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_worker_skill_subcategories_sub_category_skill_id"),
        table_name="worker_skill_subcategories",
        if_exists=True,
    )
    op.drop_table("worker_skill_subcategories")
    op.drop_index(
        op.f("ix_job_postings_company_id"),
        table_name="job_postings",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_job_postings_assigned_worker_id"),
        table_name="job_postings",
        if_exists=True,
    )
    op.drop_index("idx_job_status", table_name="job_postings", if_exists=True)
    op.drop_index("idx_job_scheduled_start", table_name="job_postings", if_exists=True)
    op.drop_index(
        "idx_job_postings_location",
        table_name="job_postings",
        postgresql_using="gist",
        if_exists=True,
    )
    op.drop_table("job_postings")
    op.drop_index(
        op.f("ix_worker_skill_categories_worker_id"),
        table_name="worker_skill_categories",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_worker_skill_categories_category_skill_id"),
        table_name="worker_skill_categories",
        if_exists=True,
    )
    op.drop_table("worker_skill_categories")
    op.drop_table("sub_category_skills")
    op.drop_index(
        op.f("ix_company_documents_document_type"),
        table_name="company_documents",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_company_documents_company_id"),
        table_name="company_documents",
        if_exists=True,
    )
    op.drop_table("company_documents")
    op.drop_index(
        op.f("ix_company_bank_details_company_id"),
        table_name="company_bank_details",
        if_exists=True,
    )
    op.drop_table("company_bank_details")
    op.drop_index(
        op.f("ix_company_addresses_company_id"),
        table_name="company_addresses",
        if_exists=True,
    )
    op.drop_index(
        "idx_company_addresses_location",
        table_name="company_addresses",
        postgresql_using="gist",
        if_exists=True,
    )
    op.drop_table("company_addresses")
    op.drop_index(
        op.f("ix_worker_documents_worker_id"),
        table_name="worker_documents",
        if_exists=True,
    )
    op.drop_table("worker_documents")
    op.drop_index(
        op.f("ix_worker_bank_details_worker_id"),
        table_name="worker_bank_details",
        if_exists=True,
    )
    op.drop_table("worker_bank_details")
    op.drop_index(
        op.f("ix_companies_firebase_uid"),
        table_name="companies",
        if_exists=True,
    )
    op.drop_table("companies")
    op.drop_table("category_skills")
    op.drop_index("idx_workers_location", table_name="workers", postgresql_using="gist", if_exists=True)
    op.drop_table("workers")
    op.drop_table("industry_types")
    # ### end Alembic commands ###


